version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - GEMINI_MAX_WORKERS=40
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped