version: '3.8'
services:
  busqa:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./results:/app/results
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true 