version: '3.8'
services:
  busqa:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=0
      - MALLOC_ARENA_MAX=4  
      - PYTHONHASHSEED=0
      - REDIS_URL=redis://redis:6379/0
    deploy:
      resources:
        limits:
          cpus: '8.0'  
          memory: 16G  
        reservations:
          cpus: '4.0' 
          memory: 8G  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    shm_size: 2g 
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru --tcp-backlog 65535 --save ""
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          cpus: '1.0'
          memory: 1G
    sysctls:
      - net.core.somaxconn=65535
    
volumes:
  redis_data:
