defaults:
  fallback_brand: "son_hai"
  brands_dir: "brands"

bots:
  "3794":
    brand_id: "son_hai"
    prompt_path: "brands/son_hai/prompt.md"
  "5157":
    brand_id: "long_van"
    prompt_path: "brands/long_van/prompt.md"
